[toolchain]
anchor_version = "0.31.0"
solana_version = "3.0.13"

[features]
resolution = true
skip-lint = false

[programs.localnet]
memeland_airdrop = "4uxX6uS3V9pyP3ei8NWZzz6RsqSddEhwosSqLD3ZbsVs"

[programs.devnet]
memeland_airdrop = "4uxX6uS3V9pyP3ei8NWZzz6RsqSddEhwosSqLD3ZbsVs"

[programs.mainnet]
memeland_airdrop = "4uxX6uS3V9pyP3ei8NWZzz6RsqSddEhwosSqLD3ZbsVs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "RUST_LOG=error yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/memeland_bankrun_optimized.ts"
