[toolchain]
anchor_version = "0.31.0"
solana_version = "3.0.13"

[features]
resolution = true
skip-lint = false

[programs.localnet]
memeland_airdrop = "4y6rh1SKMAGvunes2gHCeJkEkmPVDLhWYxNg8Zpd7RqH"

[programs.devnet]
memeland_airdrop = "4y6rh1SKMAGvunes2gHCeJkEkmPVDLhWYxNg8Zpd7RqH"

[programs.mainnet]
memeland_airdrop = "4y6rh1SKMAGvunes2gHCeJkEkmPVDLhWYxNg8Zpd7RqH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
