[toolchain]
anchor_version = "0.31.0"
solana_version = "3.0.13"

[features]
resolution = true
skip-lint = false

[programs.localnet]
memeland_airdrop = "CoRoXM3uPR9Mm9ES8nggW2KGnfJdGBJHh49uq7As8gaq"

[programs.devnet]
memeland_airdrop = "CoRoXM3uPR9Mm9ES8nggW2KGnfJdGBJHh49uq7As8gaq"

[programs.mainnet]
memeland_airdrop = "CoRoXM3uPR9Mm9ES8nggW2KGnfJdGBJHh49uq7As8gaq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "RUST_LOG=error yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/memeland_bankrun_optimized.ts"
